routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home')->name('home');

Route::group(['middleware' => ['auth']], function () {

    Route::get('/dash', function () {
        $title = "Dashboard";
        return view('backend.'.Auth::user()->role.'.dashboard.dashboard', compact('title'));
    })->name('dashboard');

    Route::resource('session_manager', 'SessionManagerController');
    Route::get('session_activate/{id}', 'SessionManagerController@active')->name('session.active');
    Route::get('session_list', 'SessionManagerController@list')->name('session.list');

    Route::resource('class', 'ClassController');
    Route::get('class_list', 'ClassController@list')->name('class.list');

    Route::resource('section', 'SectionController');
    Route::get('/section/destroy/{sectionId}', 'SectionController@destroy')->name('section.destroy');

    Route::resource('teacher', 'TeacherController');
    Route::get('teacher_permission/{teacher_id}', 'TeacherController@assigned_permissions')->name('teacher.permission');

    Route::resource('department', 'DepartmentController');
    Route::get('department_list', 'DepartmentController@list')->name('department.list');

    Route::resource('parent', 'ParentController');
    Route::get('parent_list', 'ParentController@list')->name('parent.list');

    Route::resource('accountant', 'AccountantController');
    Route::get('accountant_list', 'AccountantController@list')->name('accountant.list');

    Route::resource('librarian', 'LibrarianController');
    Route::get('librarian_list', 'LibrarianController@list')->name('librarian.list');

    Route::resource('permission', 'TeacherPermissionController');
    Route::post('assign_permission', 'TeacherPermissionController@assign_permission')->name('permission.assign');

    Route::resource('role', 'RoleController');
    Route::get('accessibility/{role}', 'RoleController@editAccessibility')->name('accessibility.edit');
    Route::patch('accessibility/{role}', 'RoleController@updateAccessibility')->name('accessibility.update');

    Route::resource('daily_attendance', 'DailyAttendanceController');
    Route::post('show_attendance', 'DailyAttendanceController@show')->name('daily_attendance.show_attendance');
    Route::post('student_list', 'DailyAttendanceController@students')->name('daily_attendance.students');

    Route::resource('subject', 'SubjectController');

    Route::resource('routine', 'RoutineController');
    Route::get('get_subject/{class_id}', 'RoutineController@subject')->name('routine.subject');
    Route::get('get_subject_teacher/{class_id}', 'RoutineController@teacher')->name('routine.teacher');

    Route::resource('room', 'ClassRoomController');
    Route::get('room_list', 'ClassRoomController@list')->name('room.list');

    Route::resource('pin', 'PinController');
    Route::get('pinlist', 'PinController@list')->name('pin.list');    
    Route::get('kie34nnsljusikajh_pin' , 'PinController@gpin')->name('generate.pin');
    Route::post('generate_pin' , 'PinController@generate')->name('pin.generate');

    Route::resource('book', 'BookController');
    Route::get('booklist', 'BookController@list')->name('book.list');

    Route::resource('book_issue', 'BookIssueController');
    Route::get('book_issue_list', 'BookIssueController@list')->name('book_issue.list');

    Route::get('student_list/{class_id}', 'BookIssueController@student')->name('book_issue.student');
    Route::delete('return_book/{book_id}', 'BookIssueController@return')->name('book_issue.return');

    Route::resource('exam', 'ExamController');
    Route::get('exam_list', 'ExamController@list')->name('exam.list');

    Route::resource('grade', 'GradeController');
    Route::get('grade_list', 'GradeController@list')->name('grade.list');

    Route::resource('mark', 'MarkController');
    Route::post('mark_list', 'MarkController@list')->name('mark.list');

    Route::resource('user', 'UserController');
    Route::post('user_list', 'UserController@list')->name('user.list');

    Route::resource('schools', 'SchoolController');
    Route::get('schools_list', 'SchoolController@list')->name('schools.list');
    Route::patch('schools_update/{id}', 'SchoolController@school_settings_update')->name('schools.update');

    Route::resource('syllabus', 'SyllabusController');
    Route::get('download_syllabus/{file}', 'SyllabusController@download')->name('syllabus.download');

    Route::resource('event_calendar', 'EventCalendarController');
    Route::get('event_calendar_list', 'EventCalendarController@list')->name('event_calendar.list');
    Route::get('event_calendar_all', 'EventCalendarController@all')->name('event_calendar.all');

    Route::resource('profile', 'ProfileController');

    //Office365
    Route::get('login/auth/office365', 'OfficeController@signin')->name('login.auth.office365');
    Route::get('redirect', 'OfficeController@redirect')->name('redirect');

    //paystack.co
    //Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');
    //Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');

    #rave flutterwave
    Route::post('/pay', 'RaveController@initialize')->name('pay');
    Route::post('/rave/callback', 'RaveController@callback')->name('callback');
    Route::get('/rave/callback', 'RaveController@callback')->name('callback');
    Route::post('/receivepayment', 'RaveController@webhook')->name('webhook');
    //Route::get('/receivepayment', 'RaveController@webhook')->name('webhook');
    Route::post('/verify', 'RaveController@verify')->name('verify');
    //Route::get('/verify', 'RaveController@verify')->name('verify');

    //jinx
    Route::resource('payment' , 'PaymentController');
    Route::get('/success', 'PaymentController@success')->name('success');
    Route::get('/fail', 'PaymentController@fail')->name('fail');

    //lesson
    Route::get('course/{slug}', ['uses' => 'CoursesController@show', 'as' => 'courses.show']);
    //Route::post('course/payment', ['uses' => 'CoursesController@payment', 'as' => 'courses.payment']);
    Route::post('course/{course_id}/rating', ['uses' => 'CoursesController@rating', 'as' => 'courses.rating']);

    Route::get('lesson/{course_id}/{slug}', ['uses' => 'LessonsController@show', 'as' => 'lessons.show']);
    Route::post('lesson/{slug}/test', ['uses' => 'LessonsController@test', 'as' => 'lessons.test']);

    //lesson admin

    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('lessons', 'Admin\LessonsController');
    Route::post('lessons_mass_destroy', ['uses' => 'Admin\LessonsController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::post('lessons_restore/{id}', ['uses' => 'Admin\LessonsController@restore', 'as' => 'lessons.restore']);
    Route::delete('lessons_perma_del/{id}', ['uses' => 'Admin\LessonsController@perma_del', 'as' => 'lessons.perma_del']);
    Route::resource('questions', 'Admin\QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'Admin\QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::post('questions_restore/{id}', ['uses' => 'Admin\QuestionsController@restore', 'as' => 'questions.restore']);
    Route::delete('questions_perma_del/{id}', ['uses' => 'Admin\QuestionsController@perma_del', 'as' => 'questions.perma_del']);
    Route::resource('questions_options', 'Admin\QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'Admin\QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::post('questions_options_restore/{id}', ['uses' => 'Admin\QuestionsOptionsController@restore', 'as' => 'questions_options.restore']);
    Route::delete('questions_options_perma_del/{id}', ['uses' => 'Admin\QuestionsOptionsController@perma_del', 'as' => 'questions_options.perma_del']);
    Route::resource('test', 'Admin\TestsController');
    Route::post('tests_mass_destroy', ['uses' => 'Admin\TestsController@massDestroy', 'as' => 'tests.mass_destroy']);
    Route::post('tests_restore/{id}', ['uses' => 'Admin\TestsController@restore', 'as' => 'tests.restore']);
    Route::delete('tests_perma_del/{id}', ['uses' => 'Admin\TestsController@perma_del', 'as' => 'tests.perma_del']);
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    //end lesson admin

    #live lessons
    Route::resource('live_lessons', 'Livelessons');
    Route::get('lesson_s', 'Livelessons@home')->name('lesson.s');
    Route::get('live_lesson_list', 'Livelessons@list')->name('live_lesson_list.list');
    Route::post('live_lesson_start', 'Livelessons@meetup')->name('live_lesson_start.meetup');
    Route::get('live_lesson_start', 'Livelessons@meetup')->name('live_lesson_start.meetup');

});

Auth::routes();
Route::get('login', 'Auth\LoginController@signon')->name('login');    

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    //
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;
use Auth;
use App\User;
use Hash;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $name = Auth::user()->other_name.' '.Auth::user()->first_name.' '.Auth::user()->middle_name;
        $title = $name;
        return view('backend.'.Auth::user()->role.'.profile.index', compact('title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Profile  $profile
     * @return \Illuminate\Http\Response
     */
    public function show(Profile $profile)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Profile  $profile
     * @return \Illuminate\Http\Response
     */
    public function edit(Profile $profile)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Profile  $profile
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $type)
    {
        $user = Auth::user();
        if($type == 'profile') {
            
            $user->first_name = $request->first_name;
            $user->other_name = $request->other_name;
            $user->middle_name = $request->middle_name;
            $user->phone = $request->phone;
            $user->address = $request->address;
                if ($request->hasFile('user_image')) {
                    $id = $user->id;
                    $dir  = 'backend/images/user_image';
                    $user_image = $request->file('user_image');
                    $user_image->move($dir, $id.".jpg");
                }
                
                $user->save();
                flash(translate('profile_has_been_successfully'))->success();
                
        }elseif($type == 'password') {
            $hasher = app('hash');
            if ($hasher->check($request->old_password, $user->password)) {
                if($request->new_password == $request->confirm_password) {
                    $user->password = Hash::make($request->confirm_password);
                    $user->save();

                    flash(translate('password_has_been_updated_successfully'))->success();
               
                     }else 
                     {
                        flash('password_mismatched')->error();
                    }
                        
                    }else{
                        flash('password_mismatched')->error();
                    }

                }
                    return redirect()->back();
                    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Profile  $profile
     * @return \Illuminate\Http\Response
     */
    public function destroy(Profile $profile)
    {
        //
    }
}

resources/views/backend/supreme/profile/edit.blade.php
<div class="row justify-content-md-center">
    <div class="col-xl-10 col-lg-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">{{ translate('update_profile') }}</h4>
                <form method="POST" class="col-12 profileAjaxForm" action="{{ route('profile.update', 'profile') }}" id = "profileAjaxForm" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="col-12">
                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="name"> {{ translate('first_name') }}</label>
                            <div class="col-md-9">
                                <input type="text" id="name" name="first_name" class="form-control"  value="{{ Auth::user()->first_name }}" required>
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="name"> {{ translate('last_name') }}</label>
                            <div class="col-md-9">
                                <input type="text" id="name" name="other_name" class="form-control"  value="{{ Auth::user()->other_name }}" required>
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="name"> {{ translate('other_name') }}</label>
                            <div class="col-md-9">
                                <input type="text" id="name" name="middle_name" class="form-control"  value="{{ Auth::user()->middle_name }}" >
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="email">{{ translate('email') }}</label>
                            <div class="col-md-9">
                                <input type="email" id="email" name="email" class="form-control"  value="{{ Auth::user()->email }}" disabled>
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="phone"> {{ translate('phone') }}</label>
                            <div class="col-md-9">
                                <input type="text" id="phone" name="phone" class="form-control"  value="{{ Auth::user()->phone }}" required>
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="address"> {{ translate('address') }}</label>
                            <div class="col-md-9">
                                <textarea class="form-control" id="address" name = "address" rows="5" required>{{ Auth::user()->address }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="example-fileinput"> {{ translate('update_user_image') }}</label>
                            <div class="col-md-9">
                                <input type="file" id="example-fileinput" name="user_image" class="form-control-file">
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-secondary col-xl-4 col-lg-4 col-md-12 col-sm-12" onclick="updateProfileInfo()">{{ translate('update_profile') }}</button>
                        </div>
                    </div>
                </form>

            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div>

    <div class="col-xl-10 col-lg-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">{{ translate('change_password') }}</h4>
                <form method="POST" class="col-12 changePasswordAjaxForm" action="{{ route('profile.update', 'password') }}" id = "changePasswordAjaxForm" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="col-12">
                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="name"> {{ translate('old_password') }}</label>
                            <div class="col-md-9">
                                <input type="password" id="old_password" name="old_password" class="form-control"  value="" required>
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="name"> {{ translate('new_password') }}</label>
                            <div class="col-md-9">
                                <input type="password" id="new_password" name="new_password" class="form-control"  value="" required>
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            <label class="col-md-3 col-form-label" for="name"> {{ translate('confirm_password') }}</label>
                            <div class="col-md-9">
                                <input type="password" id="confirm_password" name="confirm_password" class="form-control"  value="" required>
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-secondary col-xl-4 col-lg-4 col-md-12 col-sm-12" onclick="changePassword()">{{ translate('change_password') }}</button>
                        </div>
                    </div>
                </form>

            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div>
</div>

resources/views/backend/supreme/profile/index.blade.php
@extends('backend.layout.main-s')
@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title"> <i class="mdi mdi-settings title_icon"></i>{{ translate('manage_profile') }}</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div id = "profile_content" class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
            @include('backend.'.Auth::user()->role.'.profile.edit')
        </div>
    </div>
@endsection


@section('scripts')
    <script>
            function updateProfileInfo() {
                $(".profileAjaxForm").validate({});
                $(".profileAjaxForm").submit(function(e) {
                    var form = $(this);
                    ajaxSubmit(e, form, reload);
                });
            }

            function changePassword() {
                $(".changePasswordAjaxForm").validate({});
                $(".changePasswordAjaxForm").submit(function(e) {
                    var form = $(this);
                    ajaxSubmit(e, form, reload);
                });
            }

            function reload() {
                setTimeout(
                function()
                {
                    location.reload();
                }, 1000);
            }
    </script>
@endsection