routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home')->name('home');

Route::group(['middleware' => ['auth']], function () {

    Route::get('/dash', function () {
        $title = "Dashboard";
        return view('backend.'.Auth::user()->role.'.dashboard.dashboard', compact('title'));
    })->name('dashboard');

    Route::resource('session_manager', 'SessionManagerController');
    Route::get('session_activate/{id}', 'SessionManagerController@active')->name('session.active');
    Route::get('session_list', 'SessionManagerController@list')->name('session.list');

    Route::resource('class', 'ClassController');
    Route::get('class_list', 'ClassController@list')->name('class.list');

    Route::resource('section', 'SectionController');
    Route::get('/section/destroy/{sectionId}', 'SectionController@destroy')->name('section.destroy');

    Route::resource('teacher', 'TeacherController');
    Route::get('teacher_permission/{teacher_id}', 'TeacherController@assigned_permissions')->name('teacher.permission');

    Route::resource('department', 'DepartmentController');
    Route::get('department_list', 'DepartmentController@list')->name('department.list');

    Route::resource('parent', 'ParentController');
    Route::get('parent_list', 'ParentController@list')->name('parent.list');

    Route::resource('accountant', 'AccountantController');
    Route::get('accountant_list', 'AccountantController@list')->name('accountant.list');

    Route::resource('librarian', 'LibrarianController');
    Route::get('librarian_list', 'LibrarianController@list')->name('librarian.list');

    Route::resource('permission', 'TeacherPermissionController');
    Route::post('assign_permission', 'TeacherPermissionController@assign_permission')->name('permission.assign');

    Route::resource('role', 'RoleController');
    Route::get('accessibility/{role}', 'RoleController@editAccessibility')->name('accessibility.edit');
    Route::patch('accessibility/{role}', 'RoleController@updateAccessibility')->name('accessibility.update');

    Route::resource('daily_attendance', 'DailyAttendanceController');
    Route::post('show_attendance', 'DailyAttendanceController@show')->name('daily_attendance.show_attendance');
    Route::post('student_list', 'DailyAttendanceController@students')->name('daily_attendance.students');

    Route::resource('subject', 'SubjectController');

    Route::resource('routine', 'RoutineController');
    Route::get('get_subject/{class_id}', 'RoutineController@subject')->name('routine.subject');
    Route::get('get_subject_teacher/{class_id}', 'RoutineController@teacher')->name('routine.teacher');

    Route::resource('room', 'ClassRoomController');
    Route::get('room_list', 'ClassRoomController@list')->name('room.list');

    Route::resource('pin', 'PinController');
    Route::get('pinlist', 'PinController@list')->name('pin.list');    
    Route::get('kie34nnsljusikajh_pin' , 'PinController@gpin')->name('generate.pin');
    Route::post('generate_pin' , 'PinController@generate')->name('pin.generate');

    Route::resource('book', 'BookController');
    Route::get('booklist', 'BookController@list')->name('book.list');

    Route::resource('book_issue', 'BookIssueController');
    Route::get('book_issue_list', 'BookIssueController@list')->name('book_issue.list');

    Route::get('student_list/{class_id}', 'BookIssueController@student')->name('book_issue.student');
    Route::delete('return_book/{book_id}', 'BookIssueController@return')->name('book_issue.return');

    Route::resource('exam', 'ExamController');
    Route::get('exam_list', 'ExamController@list')->name('exam.list');

    Route::resource('grade', 'GradeController');
    Route::get('grade_list', 'GradeController@list')->name('grade.list');

    Route::resource('mark', 'MarkController');
    Route::post('mark_list', 'MarkController@list')->name('mark.list');

    Route::resource('user', 'UserController');
    Route::post('user_list', 'UserController@list')->name('user.list');

    Route::resource('schools', 'SchoolController');
    Route::get('schools_list', 'SchoolController@list')->name('schools.list');
    Route::patch('schools_update/{id}', 'SchoolController@school_settings_update')->name('schools.update');

    Route::resource('syllabus', 'SyllabusController');
    Route::get('download_syllabus/{file}', 'SyllabusController@download')->name('syllabus.download');

    Route::resource('event_calendar', 'EventCalendarController');
    Route::get('event_calendar_list', 'EventCalendarController@list')->name('event_calendar.list');
    Route::get('event_calendar_all', 'EventCalendarController@all')->name('event_calendar.all');

    Route::resource('profile', 'ProfileController');

    //Office365
    Route::get('login/auth/office365', 'OfficeController@signin')->name('login.auth.office365');
    Route::get('redirect', 'OfficeController@redirect')->name('redirect');

    //paystack.co
    //Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');
    //Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');

    #rave flutterwave
    Route::post('/pay', 'RaveController@initialize')->name('pay');
    Route::post('/rave/callback', 'RaveController@callback')->name('callback');
    Route::get('/rave/callback', 'RaveController@callback')->name('callback');
    Route::post('/receivepayment', 'RaveController@webhook')->name('webhook');
    //Route::get('/receivepayment', 'RaveController@webhook')->name('webhook');
    Route::post('/verify', 'RaveController@verify')->name('verify');
    //Route::get('/verify', 'RaveController@verify')->name('verify');

    //jinx
    Route::resource('payment' , 'PaymentController');
    Route::get('/success', 'PaymentController@success')->name('success');
    Route::get('/fail', 'PaymentController@fail')->name('fail');

    //lesson
    Route::get('course/{slug}', ['uses' => 'CoursesController@show', 'as' => 'courses.show']);
    //Route::post('course/payment', ['uses' => 'CoursesController@payment', 'as' => 'courses.payment']);
    Route::post('course/{course_id}/rating', ['uses' => 'CoursesController@rating', 'as' => 'courses.rating']);

    Route::get('lesson/{course_id}/{slug}', ['uses' => 'LessonsController@show', 'as' => 'lessons.show']);
    Route::post('lesson/{slug}/test', ['uses' => 'LessonsController@test', 'as' => 'lessons.test']);

    //lesson admin

    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('lessons', 'Admin\LessonsController');
    Route::post('lessons_mass_destroy', ['uses' => 'Admin\LessonsController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::post('lessons_restore/{id}', ['uses' => 'Admin\LessonsController@restore', 'as' => 'lessons.restore']);
    Route::delete('lessons_perma_del/{id}', ['uses' => 'Admin\LessonsController@perma_del', 'as' => 'lessons.perma_del']);
    Route::resource('questions', 'Admin\QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'Admin\QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::post('questions_restore/{id}', ['uses' => 'Admin\QuestionsController@restore', 'as' => 'questions.restore']);
    Route::delete('questions_perma_del/{id}', ['uses' => 'Admin\QuestionsController@perma_del', 'as' => 'questions.perma_del']);
    Route::resource('questions_options', 'Admin\QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'Admin\QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::post('questions_options_restore/{id}', ['uses' => 'Admin\QuestionsOptionsController@restore', 'as' => 'questions_options.restore']);
    Route::delete('questions_options_perma_del/{id}', ['uses' => 'Admin\QuestionsOptionsController@perma_del', 'as' => 'questions_options.perma_del']);
    Route::resource('test', 'Admin\TestsController');
    Route::post('tests_mass_destroy', ['uses' => 'Admin\TestsController@massDestroy', 'as' => 'tests.mass_destroy']);
    Route::post('tests_restore/{id}', ['uses' => 'Admin\TestsController@restore', 'as' => 'tests.restore']);
    Route::delete('tests_perma_del/{id}', ['uses' => 'Admin\TestsController@perma_del', 'as' => 'tests.perma_del']);
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    //end lesson admin

    #live lessons
    Route::resource('live_lessons', 'Livelessons');
    Route::get('lesson_s', 'Livelessons@home')->name('lesson.s');
    Route::get('live_lesson_list', 'Livelessons@list')->name('live_lesson_list.list');
    Route::post('live_lesson_start', 'Livelessons@meetup')->name('live_lesson_start.meetup');
    Route::get('live_lesson_start', 'Livelessons@meetup')->name('live_lesson_start.meetup');

});

Auth::routes();
Route::get('login', 'Auth\LoginController@signon')->name('login');    

app/Exam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Exam extends Model
{
    //
}

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use App\Exam;
use Auth;
use Illuminate\Http\Request;

class ExamController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = translate('exam');
        return view('backend.'.Auth::user()->role.'.exam.index', compact('title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.'.Auth::user()->role.'.exam.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $exam = new Exam;
        $exam->name = $request->name;
        $exam->starting_date = strtotime($request->starting_date);
        $exam->ending_date = strtotime($request->ending_date);
        $exam->school_id = school_id();
        $exam->session = get_schools();

        if($exam->save()){
            flash(translate('exam_added_successfully'))->success();
               
        }else {
            flash('an_error_occured_when_adding_exam')->error();
            
        }

        return redirect()->back();
           
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function show(Exam $exam)
    {
        //
    }

    public function list()
    {
        return view('backend.'.Auth::user()->role.'.exam.list')->render();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $exam = Exam::find($id);
        return view('backend.'.Auth::user()->role.'.exam.edit', compact('exam'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $exam = Exam::find($id);
        $exam->name = $request->name;
        $exam->starting_date = strtotime($request->starting_date);
        $exam->ending_date = strtotime($request->ending_date);
        $exam->school_id = school_id();
        $exam->session = get_schools();
        if($exam->save()){

            flash(translate('exam_updated_successfully'))->success();
               
        }else {
            flash('an_error_occured_when_updating_exam')->error();
            
        }

        return redirect()->back();
            
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Exam::destroy($id)){

            flash(translate('exam_deleted_successfully'))->success();
               
        }else {
            flash('an_error_occured_when_deleting_exam')->error();
            
        }

        return redirect()->back();
            
    }
}

resources/views/backend/superadmin/exam/create.blade.php
<form method="POST" class="d-block ajaxForm" action="{{ route('exam.store') }}">
    @csrf

    <div class="form-group col-md-12">
        <label for="name">{{ translate('exam_name') }}</label>
        <input type="text" class="form-control" id="name" name = "name" required>
        <small id="name_help" class="form-text text-muted">{{ translate('provide_exam_name') }}.</small>
    </div>

    <div class="form-group col-md-12">
        <label for="starting_date">{{ translate('exam_starting_date') }}</label>
        <input type="text" class="form-control date" id="starting_date" data-toggle="date-picker" data-single-date-picker="true" name = "starting_date" value="" required>
        <small id="date_help" class="form-text text-muted">{{ translate('provide_exam_date') }}.</small>
    </div>
    <div class="form-group col-md-12">
        <label for="ending_date">{{ translate('exam_ending_date') }}</label>
        <input type="text" class="form-control date" id="ending_date" data-toggle="date-picker" data-single-date-picker="true" name = "ending_date" value="" required>
        <small id="date_help" class="form-text text-muted">{{ translate('provide_exam_date') }}.</small>
    </div>

    <div class="form-group  col-md-12">
        <button class="btn btn-block btn-primary" type="submit">Save Exam</button>
    </div>
</form>

<script>
    $(document).ready(function() {
        $('#starting_date').daterangepicker();
        $('#ending_date').daterangepicker();
    });

    $(".ajaxForm").validate({}); // Jquery form validation initialization
    $(".ajaxForm").submit(function(e) {
        var form = $(this);
        ajaxSubmit(e, form, showAllExams);
    });

</script>

resources/views/backend/superadmin/exam/edit.blade.php
<form method="POST" class="d-block ajaxForm" action="{{ route('exam.update', $exam->id) }}">
    @csrf
    @method('PATCH')
    <div class="form-group col-md-12">
        <label for="name">{{ translate('exam_name') }}</label>
        <input type="text" class="form-control" id="name" name = "name" value="{{ $exam->name }}" required>
        <small id="name_help" class="form-text text-muted">{{ translate('provide_exam_name') }}.</small>
    </div>

    <div class="form-group col-md-12">
        <label for="starting_date">{{ translate('exam_starting_date') }}</label>
        <input type="text" class="form-control date" id="starting_date" data-toggle="date-picker" data-single-date-picker="true" name = "starting_date" value="{{ date('m/d/Y', $exam->starting_date) }}" required>
        <small id="date_help" class="form-text text-muted">{{ translate('provide_exam_date') }}.</small>
    </div>

    <div class="form-group col-md-12">
        <label for="ending_date">{{ translate('exam_ending_date') }}</label>
        <input type="text" class="form-control date" id="ending_date" data-toggle="date-picker" data-single-date-picker="true" name = "ending_date" value="{{ date('m/d/Y', $exam->ending_date) }}" required>
        <small id="date_help" class="form-text text-muted">{{ translate('provide_exam_date') }}.</small>
    </div>

    <div class="form-group  col-md-12">
        <button class="btn btn-block btn-primary" type="submit">{{ translate('update_exam') }}</button>
    </div>
</form>

<script>
    $(document).ready(function() {
        $('#starting_date').daterangepicker();
        $('#ending_date').daterangepicker();
    });

    $(".ajaxForm").validate({}); // Jquery form validation initialization
    $(".ajaxForm").submit(function(e) {
        var form = $(this);
        ajaxSubmit(e, form, showAllExams);
    });
</script>

resources/views/backend/superadmin/exam/index.blade.php
@extends('backend.layout.main')
@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title"> <i class="mdi mdi-grease-pencil title_icon"></i> {{ translate('exam') }}
                <button type="button" class="btn btn-icon btn-success mb-1 btn-rounded alignToTitle" onclick="showAjaxModal('{{ route('exam.create') }}', '{{ translate('Create New Exam') }}')"> <i class="mdi mdi-plus"></i> {{ translate('add_exam') }} </button></h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row ">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <div id = "exam_content">
                        @include('backend.'.Auth::user()->role.'.exam.list')
                    </div> <!-- end table-responsive-->
                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
@endsection

@section('scripts')
<script>
    var showAllExams = function () {
        var url = '{{ route("exam.list") }}';

        $.ajax({
            type : 'GET',
            url: url,
            success : function(response) {
                $('#exam_content').html(response);
                initDataTable("basic-datatable");
            }
        });
    }
</script>
@endsection

resources/views/backend/superadmin/exam/list.blade.php
@php
    $exams = App\Exam::where('school_id', school_id())->where('session', get_schools())->get();
@endphp
@if (count($exams) > 0)
<div class="table-responsive-sm">
    <table id="basic-datatable" class="table table-striped dt-responsive nowrap" width="100%">
        <thead class="thead-dark">
        <tr>
            <th>{{ translate('name') }}</th>
            <th>{{ translate('starting_date') }}</th>
            <th>{{ translate('ending_date') }}</th>
            <th>{{ translate('option') }}</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($exams as $exam)
            <tr>
                <td>{{ $exam->name }}</td>
                <td>
                    {{ date('D, d-M-Y', $exam->starting_date) }}
                </td>
                <td>
                    {{ date('D, d-M-Y', $exam->ending_date) }}
                </td>
                <td>
                    <div class="btn-group mb-2">
                        <button type="button" class="btn btn-icon btn-secondary btn-sm" style="margin-right:5px;" onclick="showAjaxModal('{{ route('exam.edit', $exam->id) }}', '{{ translate('Update Exam') }}')" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{ translate('Update Exam info') }}"> <i class="mdi mdi-wrench"></i> </button>
                        <button type="button" class="btn btn-icon btn-dark btn-sm" style="margin-right:5px;" onclick="confirm_modal('{{ route('exam.destroy', $exam->id) }}', showAllExams )" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{ translate('Delete Exam') }}"> <i class="mdi mdi-window-close"></i> </button>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@else
    <div style="text-align: center;">
            <img src="{{ asset('backend/images/no-data.png') }}" alt="" class="empty-box">
            <p>{{ translate('no_data_found') }}</p>
    </div>
@endif